---
- name: Descargar archivos YAML de addons de Istio
  get_url:
    url: "https://github.com/istio/istio/raw/main/samples/addons/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - grafana.yaml
    - jaeger.yaml
    - loki.yaml
    - prometheus.yaml

- name: Aplicar addons de Istio
  command: kubectl apply -f "/tmp/{{ item }}"
  with_items:
    - grafana.yaml
    - jaeger.yaml
    - loki.yaml
    - prometheus.yaml
